### ISSUE TITLE
Support CMake build system

### ISSUE THREAD

**Issue by utilForever** [utilForever/CubbyFlow-v1#209]
- CubbyFlow
- cnpy
- googletest
- obj
- pystring
- winix
- UnitTests
- ManualTests
- HelloFluidSim
- HybridLiquidSim
- LevelSetLiquidSim
- Obj2Sdf
- Particles2Obj
- Particles2Xml
- SmokeSim
- SPHSim

**Comment by ghost** [comment]
I would be glad to implement it :3 I have some experience in writing cross platform cmake scripts... Should I submit a pull request maybe?

**Comment by utilForever** [comment]
@MattMatt2000 Thank you for your consideration. It is already working, so we will complete it soon.
