### ISSUE TITLE
Fix heap corruption in manual tests on macOS 64-bit build

### ISSUE THREAD

**Issue by utilForever** [utilForever/CubbyFlow-v1#217]
- Log
```
[----------] 4 tests from APICSolver3Tests
[ RUN      ] APICSolver3Tests.WaterDrop
[       OK ] APICSolver3Tests.WaterDrop (33582 ms)
[ RUN      ] APICSolver3Tests.DamBreakingWithCollider
ManualTests(4353,0x700008db7000) malloc: * error for object 0x7ff9a84197b0: double free
* set a breakpoint in malloc_error_break to debug
[1]    4353 abort      ./ManualTests
```

```
[----------] 4 tests from FLIPSolver3Tests
[ RUN      ] FLIPSolver3Tests.WaterDrop
[       OK ] FLIPSolver3Tests.WaterDrop (32374 ms)
[ RUN      ] FLIPSolver3Tests.DamBreakingWithCollider
ManualTests(2837,0x70000209b000) malloc: * error for object 0x7ff84f900038: incorrect checksum for freed object - object was probably modified after being freed.
* set a breakpoint in malloc_error_break to debug
[1]    2837 abort      ./ManualTests
```

**Comment by doyubkim** [comment]
Can you reproduce this error with the original test from Jet Framework as well? If not, what would be the delta between two codebase?

**Comment by utilForever** [comment]
@doyubkim I'll check it.

**Comment by utilForever** [comment]
@doyubkim I think Jet Framework seems to have no problems. In the case of CubbyFlow, there is only a problem with manual tests starts with DamBreaking. 🤔

**Comment by utilForever** [comment]
@doyubkim It seems to be an intermittent problem. Occasionally, errors such as segmentation fault, bus error, and double free occur, but sometimes they work fine. (I'll check another Macbook.)

**Comment by doyubkim** [comment]
You mean from this project (CubbyFlow), right?
Usually that happens when you’re writing something outside a malloced region. If lucky, it may not crash, but it’s definitely a heap memory access issue. I’m pretty sure there is a loop that iterates greater range than it supposed to run. Or maybe there’s an unsigned integer overflow where the integer is used for array indexing. Print out some messages for each computation step and see where it crashes.

**Comment by utilForever** [comment]
@doyubkim I'll check it. Thanks. :+1:

**Comment by utilForever** [comment]
![25353094_1984192495168917_863535975_o](https://user-images.githubusercontent.com/5622661/33949216-5698ffc6-e06c-11e7-8d6f-d3c603dace39.png)
![25359892_1984149378506562_1770774562_n](https://user-images.githubusercontent.com/5622661/33949217-56be7b70-e06c-11e7-907e-cc719a34265a.png)

**Comment by utilForever** [comment]
@doyubkim I ran manual tests of fluid-engine-dev several times. Eventually, I noticed that I found the same problem in the Jet. Can you test it several times? Thanks.
Note) This problem only occurs with DamBrakingWithCollider (APICSolver3/PICSolver3/FLIPSolver3).

**Comment by doyubkim** [comment]
This might be related to the MatrixCsr code. I recently fixed some assertion issues so please try again with the latest master from Jet.

**Comment by utilForever** [comment]
@doyubkim Okay. I'll test again later. Thanks.

**Comment by doyubkim** [comment]
PR for the fix is posted on Jet's repo. That should solve this problem.

**Comment by utilForever** [comment]
@doyubkim It was a race condition problem. I was thinking that each time I ran the test, there was a problem in different places and it was a thread related problem. I thought about using a mutex, but it was not too efficient and I was trying to find another way. Thank you for resolving. I'll test it. :^)
