### ISSUE TITLE
Compressed linear system solver for FDM solvers (Jet #124)

### ISSUE THREAD

**Issue by utilForever** [utilForever/CubbyFlow-v1#223]
Base PR : doyubkim/fluid-engine-dev#124
- Lets CSR matrix to be used for FDM solvers.

**Comment by doyubkim** [comment]
For the issues/commits that are porting Jet Framework commits, I suggest you to mention that specific commit IDs or the PRs from the original repo in the tickets. That way you can track any new issues / regressions (ex. the heap memory issue) much easier and also distinguish what’s CubbyFlow specific feature and what’s been transferred from Jet. Also, this particular ticket shows the commit message from Jet which already talks about the perf result, but it’s under todo bucket in CubbyFlow repo which can be confusing for the trackers. You can first mention your original message and then quote the commit message with some Markdown tags.

**Comment by utilForever** [comment]
@doyubkim It's a great idea. I didn't realize that I could confuse other people. I'll add a separate PR to the ticket that is reflected in the Jet project. Thank you for your feedback, and I apologize for the inconvenience.

**Comment by utilForever** [comment]
@doyubkim I added Jet PR to the CubbyFlow issue title and marked it separately in the content of the issue. Does it look better?

**Comment by doyubkim** [comment]
Thanks! If you can put actual URL to the PR or commit, that would be even better for navigation :)

**Comment by utilForever** [comment]
@doyubkim I put the base PR as a link in the issue contents. :^)
Update) Did you mean to add URL address when you PR or commit in CubbyFlow project? If so, I was misunderstanding. I'll do that when I commit.

**Comment by doyubkim** [comment]
Actually, never mind about my comment on URLs. it was CodeHub's (iOS app for GitHub) issue that was not displaying the link properly. I can see the link correctly from web browsers now.

**Comment by utilForever** [comment]
@doyubkim Okay. Thank you.
