### ISSUE TITLE
Bottleneck optimization for fixed-sized memory accesses

### ISSUE THREAD

**Issue by ArtBlnd** [utilForever/CubbyFlow-v1#249]
https://github.com/utilForever/CubbyFlow/blob/8a31281f44dbe292695effae34b4f73659e8c808/Includes/Core/Math/Quaternion-Impl.h#L77-L87

This code is an example for vectorize optimizing, accessing each memory all time will cause much slower performance for copying.

Im suggesting 3 solutions to avoid those bottlenecks.

Before we solving issues
-------------------------

Change
```
T w;
T x;
T y;
T z;
```
Into
```
struct {
    T w;
    T x;
    T y;
    T z;
} data;
```
For protecting any other class structures.

First solution
------------------
Use `simd` instructions instead of `operator=`

Changes copy code into simd intrins
```
assert(list.size() == 4);
auto inputElem = list.begin();

_m256 XMM = __mm256_load_ps(&inputElm);
__mm256_store_ps(&data, XMM);
```

This will need a specialization for each size, float, double.

Second solution
--------------------

Make it into a loop. 

```
assert(list.size() == 4);
auto inputElem = list.begin();

T* arrData = &data;
for(auto i = 0; i < 4; ++i)
    arrData[i] = inputElem[i];
```

Do compiler auto vectorization.

Third solution
-----------------

Use library support vector classes.
such as Vec3f in OpenGL.

End
---------------------

Changing all of these bottlenecks will make performance lot better.

**Comment by utilForever** [comment]
It is not so good to access the members of a math class, such as ```Quaternion```, by binding structs to ```data```. When you do calculations, you have direct access to the members, but it is not intuitive to access them once more through ```data```.
But the problem you have raised seems reasonable. So, let me think more about how to solve it.
